# ランダムフォレストによる予測

In [41]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

### 読み込むデータファイルの年を入力

In [81]:
target_year = '2019'

In [82]:
read_file_name = target_year + '_result.pickle'
data = pd.read_pickle(read_file_name)

In [83]:
data.head(2)

,着順,枠番,馬番,馬名,斤量,騎手,単勝,人気,course_len,weather,race_type,ground_state,date,性,年齢,体重,増減
201901010101,1,1,1,ゴルコンダ,54.0,ルメール,1.4,1.0,1800,曇,芝,良,2019-07-27,牡,2,518,-16
201901010101,2,3,3,プントファイヤー,54.0,岩田康誠,3.5,2.0,1800,曇,芝,良,2019-07-27,牡,2,496,-8

In [84]:
data.drop('馬名', axis=1, inplace=True)

In [99]:
data['course_len'] = data['course_len'].astype(int)
data['年齢'] = data['年齢'].astype(int)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47118 entries, 201901010101 to 201910021212
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   着順            47118 non-null  int64
 1   枠番            47118 non-null  int64
 2   馬番            47118 non-null  int64
 3   斤量            47118 non-null  float64
 4   騎手            47118 non-null  object
 5   単勝            47118 non-null  float64
 6   人気            47118 non-null  float64
 7   course_len    47118 non-null  int64
 8   weather       47118 non-null  object
 9   race_type     47118 non-null  object
 10  ground_state  47118 non-null  object
 11  date          47118 non-null  datetime64[ns]
 12  性             47118 non-null  object
 13  年齢            47118 non-null  int64
 14  体重            47118 non-null  int64
 15  増減            47118 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(7), object(5)
memory usage: 7.1+ MB

In [100]:
data_d = pd.get_dummies(data)

In [101]:
data_d['rank'] = data_d['着順'].map(lambda x: x if x<4 else 4)

In [102]:
data_d

,着順,枠番,馬番,斤量,単勝,人気,course_len,date,年齢,体重,...,race_type_芝,race_type_障害,ground_state_不良,ground_state_稍重,ground_state_良,ground_state_重,性_セ,性_牝,性_牡,rank
201901010101,1,1,1,54.0,1.4,1.0,1800,2019-07-27,2,518,...,1,0,0,0,1,0,0,0,1,1
201901010101,2,3,3,54.0,3.5,2.0,1800,2019-07-27,2,496,...,1,0,0,0,1,0,0,0,1,2
201901010101,3,4,4,51.0,46.6,6.0,1800,2019-07-27,2,546,...,1,0,0,0,1,0,0,0,1,3
201901010101,4,8,9,51.0,56.8,7.0,1800,2019-07-27,2,458,...,1,0,0,0,1,0,0,0,1,4
201901010101,5,5,5,54.0,140.3,9.0,1800,2019-07-27,2,436,...,1,0,0,0,1,0,0,0,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201910021212,12,6,11,56.0,120.3,15.0,2600,2019-09-01,6,458,...,1,0,0,0,0,1,1,0,0,4
201910021212,13,1,1,54.0,7.5,4.0,2600,2019-09-01,5,460,...,1,0,0,0,0,1,0,0,1,4
201910021212,14,2,3,54.0,99.2,12.0,2600,2019-09-01,4,478,...,1,0,0,0,0,1,0,0,1,4
201910021212,15,6,12,52.0,17.5,8.0,2600,2019-09-01,3,468,...,1,0,0,0,0,1,0,1,0,4
201910021212,16,2,4,55.0,110.3,14.0,2600,2019-09-01,4,450,...,1,0,0,0,0,1,0,1,0,4

In [104]:
def split_data(df, test_size):
    sorted_id_list = data.sort_values('date').index.unique()
    train_id_list = sorted_id_list[:round(len(sorted_id_list) * (1- test_size))]
    test_id_list = sorted_id_list[round(len(sorted_id_list) * (1 - test_size)):]
    train = data.loc[train_id_list]
    test = data.loc[test_id_list]
    return train, test

In [105]:
train, test = split_data(data, 0.3)

In [106]:
len(train) / len(data)

0.7030646462073942

In [107]:
len(test) / len(data)

0.29693535379260577